/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Ghost(props) {
  const ref = useRef()
  const { nodes, materials } = useGLTF('/Ghosty.glb')

  //   useFrame((state, delta) => (ref.current.rotation.x += 0.005))
  //   useFrame((state, delta) => (ref.current.rotation.z += 0.005))

  return (
    <group {...props} dispose={null} position={[0, 0.5, 0]} rotation={[0, 3, 0]}>
      <mesh geometry={nodes.Body.geometry} material={materials.Ghost} />
      <mesh geometry={nodes.Sphere002.geometry} material={materials.Eyes} />
      <mesh geometry={nodes.Sphere002_1.geometry} material={materials.Pupils} />
    </group>
  )
}

useGLTF.preload('/Ghosty.glb')
